In [74]:
import numpy as np
import pandas as pd

np.random.seed(42)

# random_number_1 = np.random.random(5)
# print("first sequence: ",random_number_1)
# random_number_1 = np.random.random(5)
# print("second sequence: ",random_number_1)
# random_number_1 = np.random.random(5)
# print("third sequence: ",random_number_1)

random_2d_array = np.random.random((3, 4))
print("2D array:\n ", random_2d_array)

random_2d_array = np.random.rand(3, 4)
print("2D array:\n ", random_2d_array)


2D array:
  [[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]
2D array:
  [[0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]]


In [75]:
prices = np.round(np.random.uniform(99,100,20),2)
print("mon test de prix aléatoires entre 20 et 100: \n", prices)

mon test de prix aléatoires entre 20 et 100: 
 [99.46 99.79 99.2  99.51 99.59 99.05 99.61 99.17 99.07 99.95 99.97 99.81
 99.3  99.1  99.68 99.44 99.12 99.5  99.03 99.91]


In [76]:
reponses = np.random.choice(
    ["vraie", "faux", "aucune idée", "la question est nulle"],
    size=4,
    p=[0.4,0.4,0.15,0.05]
)

print(reponses)

['vraie' 'faux' 'vraie' 'faux']


In [77]:
# NumPy arange for float sequences with step of 0.5
decimal_sequence = np.arange(0, 10, 0.5)
print(f"Decimal sequence: {decimal_sequence}")


Decimal sequence: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [78]:
# Create an array of 25 values evenly spaced between 0 and 24
time_points = np.linspace(0, 24, 25)  # 25 points from 0 to 24 hours
print(f"Time points: {time_points[:5]} ... {time_points[-5:]}")


Time points: [0. 1. 2. 3. 4.] ... [20. 21. 22. 23. 24.]


In [79]:
# Create arrays with 0s
zero_array = np.zeros(10, dtype=int)
print(f"Zero array: {zero_array}")


Zero array: [0 0 0 0 0 0 0 0 0 0]


In [80]:
grades = {
    'kyu': [9,8,7,6,5,4,3,2,1],
    'grade_name': ["blanche", "blanche", "blanche", "blanche", "bleue", "bleue", "marron", "marron", "marron"],
    'admission_duration_inyear': [0, 0, 0, 1, 1, 2, 2, 2, 3]
}
print(grades)

{'kyu': [9, 8, 7, 6, 5, 4, 3, 2, 1], 'grade_name': ['blanche', 'blanche', 'blanche', 'blanche', 'bleue', 'bleue', 'marron', 'marron', 'marron'], 'admission_duration_inyear': [0, 0, 0, 1, 1, 2, 2, 2, 3]}


In [88]:
df_grades = pd.DataFrame(grades)
print(df_grades)

   kyu grade_name  admission_duration_inyear
0    9    blanche                          0
1    8    blanche                          0
2    7    blanche                          0
3    6    blanche                          1
4    5      bleue                          1
5    4      bleue                          2
6    3     marron                          2
7    2     marron                          2
8    1     marron                          3


In [90]:
cours_adulte = df_grades['grade_name'] != "blanche"
print(df_grades[cours_adulte])

   kyu grade_name  admission_duration_inyear
4    5      bleue                          1
5    4      bleue                          2
6    3     marron                          2
7    2     marron                          2
8    1     marron                          3


In [ ]:
df_grades.shape

(9, 3)

In [ ]:
# Generate large dataset efficiently
record_count = 10000

# Direct NumPy array generation
large_data_dict = {
    'record_id': range(1, record_count + 1),
    'category': np.random.choice(['A', 'B', 'C'], record_count),
    'value': np.random.randint(10, 100, record_count),
    'flag': np.random.choice([True, False], record_count)
}
df_large = pd.DataFrame(large_data_dict)
print(df_large.head())

   record_id category  value   flag
0          1        B     10   True
1          2        B     65  False
2          3        A     11   True
3          4        C     90   True
4          5        B     39  False


In [ ]:
# Create a date range for daily timestamps in 2026
daily_dates = pd.date_range(start='2026-01-01', end='2026-12-31', freq='D')

print(f"Daily dates count: {len(daily_dates)}")
print(f"First dates: {daily_dates[:5]}")
print(f"Last dates: {daily_dates[-5:]}")


Daily dates count: 365
First dates: DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05'],
              dtype='datetime64[us]', freq='D')
Last dates: DatetimeIndex(['2026-12-27', '2026-12-28', '2026-12-29', '2026-12-30',
               '2026-12-31'],
              dtype='datetime64[us]', freq='D')


In [ ]:
print(pd.__version__)


3.0.5


In [ ]:
monthly_date = pd.date_range(
    start='2026-01-01', 
    end='2026-12-31', 
    freq='ME'
)

print(f"Voici tous les mois de l'année {monthly_date.year[0]}: {monthly_date.month_name().to_list()}")

for m in monthly_date:
    print(m.strftime("%B %Y"))

Voici tous les mois de l'année 2026: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
January 2026
February 2026
March 2026
April 2026
May 2026
June 2026
July 2026
August 2026
September 2026
October 2026
November 2026
December 2026


In [ ]:
# Method 2: Random time deltas
base_date = pd.Timestamp('2023-01-01')
random_days = np.random.randint(0, 365, size=100)

# pd.Timedelta creates time differences to add to base date
random_timestamps = [base_date + pd.Timedelta(days=int(days)) for days in random_days]
print(f"Random timestamps sample: {random_timestamps[:5]}")



Random timestamps sample: [Timestamp('2023-02-21 00:00:00'), Timestamp('2023-02-18 00:00:00'), Timestamp('2023-04-10 00:00:00'), Timestamp('2023-09-08 00:00:00'), Timestamp('2023-02-23 00:00:00')]
