# Data Generation with Pandas and NumPy 🧮

## What you will learn in this course 🧐🧐

Now that you know the basics of Python it's time to think about data generation and manipulation. This course will teach you how to use Pandas and NumPy to structure your data so that you can analyze it effectively.

By the end of this course, you will:
* Learn how to create synthetic datasets from scratch using NumPy and Pandas
* Understand how to use random number generation to simulate realistic user behavior
* Build DataFrames using dictionaries, arrays, and functions for large-scale records
* Apply logic to assign categories, labels, and flags in your datasets
* Control data shape, length, and reproducibility with seed values and patterns
* Work with time-based data using Pandas' datetime functions and ranges

## Difference between Pandas and NumPy

You will often hear people compare **NumPy** and **Pandas**, and at first, the difference can feel unclear. 

You can think of **NumPy** as the foundation. It gives you one powerful tool: the **array**. NumPy runs fast and handles numbers very well. When you need to build algorithms, simulate data, apply linear algebra, or run numerical models, you use NumPy.

<Note type="tip" title="Linear Algebra">

In this course, you will not go deep into linear algebra, but it is useful to understand that linear algebra is a branch of mathematics that deals with **vectors, matrices, and linear transformations**. It is fundamental to many areas of data science, including machine learning, computer graphics, and scientific computing.

More here: [Linear Algebra](https://app.jedha.co/track/linear-algebra)

</Note>

But NumPy does not understand **labels**. It does not understand **columns** or **indexes** the way humans do. It works with data as a raw matrix of numbers. 

That is where **Pandas** comes in. Pandas gives you a way to work with structured data. Structured data means data that comes in rows and columns, where each column has a name and each row has a label. **Pandas builds on top of NumPy**. It gives you tools to name columns, to label rows, to filter data based on those names, and to reshape your data in ways that make sense to your analysis.

<img src="https://data-analytics-fullstack-assets.s3.eu-west-3.amazonaws.com/M05-Exploratory_Data_Analysis/M3_D1_Difference_Pandas_Numpy.png"/>

Don't worry you will understand the relationship best when you watch a **DataFrame** turn into a NumPy **array** and then back again. That transformation shows you what each library sees. **NumPy sees the numbers. Pandas sees the structure**. You need both views to work with data properly.

Let's see that in the context of **data generation** applied to **social media data**.

## Data generation with NumPy 

**Data generation involves creating synthetic datasets that mimic real-world data.** This is especially useful for testing algorithms, validating models, and conducting experiments when real data is scarce or unavailable.

To install the libraries, you can use pip in your terminal:

```bash
pip install pandas numpy
```


In [14]:
import numpy as np
import pandas as pd

# Access NumPy module
# dir(np)

In [15]:
# Access NumPy random documentation
# np.random?

### Random number generation

NumPy helps generate random numbers through specific mathematical functions. You can control the randomness with **seeds** and specify ranges, probabilities, and distributions. The same seed produces identical random sequences. This reproducibility enables testing and debugging synthetic datasets.

| Method | Description | Use Cases |
| --- | --- | --- |
| `np.random.random()` | Creates floating-point numbers between 0 and 1. You can specify the quantity. | Generates probabilities, ratios, and normalized data. |
| `np.random.rand()` | Creates floating-point numbers between 0 and 1, allowing you to specify the shape of the output array using dimensions (rows, columns). | Useful for generating matrices or multi-dimensional data. |
| `np.random.randint()` | Creates integer sequences within specified bounds. You control minimum value, maximum value, and quantity. | Generates user IDs, post IDs, and count data. |
| `np.random.uniform()` | Creates floating-point numbers within a custom range [low, high]. Unlike `np.random.random()`, you control both the lower and upper bounds. | Use this when you need realistic amounts with a specific range, such as prices between €1 and €2,500 or scores between 0 and 100. |

Let's see how to use these methods to generate synthetic social media data.

In [ ]:
# Import necessary libraries

# Control randomness with seed equal to 42 for reproducibility
np.random.seed(42)

# Generate first sequence of 5 random numbers between 0 and 1
random_numbers_1 = np.random.random(5)
print("First sequence:", random_numbers_1)

# Generate second sequence of 5 random numbers between 0 and 1
random_numbers_2 = np.random.rand(5)
print("Second sequence:", random_numbers_2)

# Generate third sequence of 5 random numbers between 0 and 1
random_numbers_3 = np.random.random(5)
print("Third sequence:", random_numbers_3)

First sequence: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Second sequence: [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
Third sequence: [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]


In [ ]:
# Generate a 2D array of random numbers using np.random.random() with shape (3, 4) 3 rows and 4 columns  # noqa: E501
random_2d_array = np.random.random((3, 4))
print("2D array using np.random.random():\n", random_2d_array)

# Generate a 2D array of random numbers using np.random.rand()
random_2d_array_alt = np.random.rand(3, 4)
print("2D array using np.random.rand():\n", random_2d_array_alt)

2D array using np.random.random():
 [[0.18340451 0.30424224 0.52475643 0.43194502]
 [0.29122914 0.61185289 0.13949386 0.29214465]
 [0.36636184 0.45606998 0.78517596 0.19967378]]
2D array using np.random.rand():
 [[0.51423444 0.59241457 0.04645041 0.60754485]
 [0.17052412 0.06505159 0.94888554 0.96563203]
 [0.80839735 0.30461377 0.09767211 0.68423303]]


<Note type="tip" title="Understanding Seeds">
By setting a seed, you ensure that the sequence of random numbers generated is **reproducible**. If you run again this notebook with the same seed, you will get the same random numbers. This is crucial for testing and debugging, as it allows you to have consistent results across different runs of your code.
</Note>

In [18]:
# Generate integer sequences
user_ids = np.random.randint(1, 1001, size=10)  # 10 user IDs between 1-1000
print("User IDs:", user_ids)

# Generate counts with different ranges
post_counts = np.random.randint(0, 101, size=20)  # Post counts 0-100
print("Post counts sample:", post_counts[:10])

# Generate categorical indices
category_indices = np.random.randint(0, 3, size=15)  # Indices for 3 categories
print("Category indices:", category_indices)

User IDs: [367 956 455 428 509 776 943  35 206  81]
Post counts sample: [35 49  3  1  5 53  3 53 92 62]
Category indices: [2 1 2 0 1 0 0 1 2 0 1 0 0 0 0]


In [19]:
# np.random.uniform() generates floats within a custom range [low, high]
transaction_amounts = np.random.uniform(1, 2500, size=10)
print("Transaction amounts (€):", np.round(transaction_amounts, 2))

Transaction amounts (€): [2005.69  187.3  2467.23 1930.84  497.59   14.8  2038.84 1767.44 1822.79
 1928.4 ]


In [ ]:
# Key difference from np.random.random(): you control both bounds
print("np.random.random(5):", np.round(np.random.random(5), 4))   # always 0 to 1
print("np.random.uniform(1, 100, 5):", np.round(np.random.uniform(1, 100, 5), 2))  # 1 to 100  # noqa: E501


np.random.random(5): [0.074  0.3585 0.1159 0.8631 0.6233]
np.random.uniform(1, 100, 5): [33.76  7.29 31.79 33.19 73.23]


### Choice selection with custom probabilities

`np.random.choice()` selects items from predefined options. You can specify selection probabilities to match real-world patterns. This method creates categorical data with **realistic distributions**.

In [21]:
# Simple random choice without probabilities
account_types_simple = np.random.choice(['personal', 'business', 'creator'], size=10)

print("Simple choice:", account_types_simple)

Simple choice: ['business' 'creator' 'creator' 'personal' 'creator' 'personal' 'creator'
 'business' 'creator' 'personal']


To simulate account types on a social media platform, with a distribution of 70% "personal," 20% "business," and 10% "creator" accounts, you can use NumPy's `np.random.choice()` function with custom probabilities.

In [ ]:
# Choice with realistic probabilities
account_types_weighted = np.random.choice(
    ['personal', 'business', 'creator'],
    size=1000,
    p=[0.7, 0.2, 0.1]  # 70% personal, 20% business, 10% creator
)

print("Weighted choice sample:", account_types_weighted[:10])

# Analyze the distribution of the weighted choices
# Series.value_counts() counts occurrences of each category
print("Weighted choice distribution:", pd.Series(account_types_weighted).value_counts())

Weighted choice sample: ['business' 'personal' 'personal' 'personal' 'business' 'personal'
 'personal' 'personal' 'business' 'personal']
Weighted choice distribution: personal    703
business    196
creator     101
Name: count, dtype: int64


Boolean data requires probability specification. `np.random.choice()` with True/False options creates boolean arrays with controlled probability distributions.

In [23]:
# Simulate 1000 verified accounts with 5% chance of being True
verified_accounts = np.random.choice([True, False], size=1000, p=[0.05, 0.95])

# Display the count of verified accounts
print(f"Verified accounts: {verified_accounts.sum()} out of {len(verified_accounts)}")


Verified accounts: 52 out of 1000


In [ ]:
# Generate profile picture presence
has_profile_pic = np.random.choice([True, False], size=1000, p=[0.9, 0.1])

# Display the count of accounts with profile pictures
print(f"Accounts with profile pic: {has_profile_pic.sum()} out of {len(has_profile_pic)}")  # noqa: E501


Accounts with profile pic: 899 out of 1000


### Array creation functions

NumPy provides advanced array creation functions beyond basic range. `np.arange()` creates float sequences. `np.linspace()` creates evenly spaced values. `np.zeros()` and `np.ones()` create arrays filled with specific values.

In [25]:
# NumPy arange for float sequences with step of 0.5
decimal_sequence = np.arange(0, 10, 0.5)
print(f"Decimal sequence: {decimal_sequence}")

Decimal sequence: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [26]:
# Create an array of 25 values evenly spaced between 0 and 24
time_points = np.linspace(0, 24, 25)  # 25 points from 0 to 24 hours
print(f"Time points: {time_points[:5]} ... {time_points[-5:]}")

Time points: [0. 1. 2. 3. 4.] ... [20. 21. 22. 23. 24.]


In [27]:
# Create arrays with 0s
zero_array = np.zeros(10, dtype=int)
print(f"Zero array: {zero_array}")

Zero array: [0 0 0 0 0 0 0 0 0 0]


In [28]:
# Create arrays with 1s
ones_array = np.ones(5, dtype=bool)
print(f"Ones array: {ones_array}")

Ones array: [ True  True  True  True  True]


In [29]:
# Full array with custom value
default_followers = np.full(100, 500)  # 100 accounts with 500 followers each
print(f"Default followers: {default_followers[:10]}")

Default followers: [500 500 500 500 500 500 500 500 500 500]


## Pandas data structure creation 

**Pandas builds DataFrames from dictionaries, lists, and arrays**. Understanding DataFrame construction enables complex data structure creation.

### Dictionary-based DataFrame creation

Dictionaries provide the most intuitive DataFrame creation method. **Dictionary keys become column names. Dictionary values become column data**. 

Values must have equal length or pandas will raise errors.

In [30]:
# Basic dictionary to DataFrame
social_data = {
    'user_id': [101, 102, 103, 104, 105],
    'username': ['luna99', 'max_power', 'sakura_chan', 'data_wolf', 'queenbee'],
    'followers': [4520, 1875, 9200, 640, 7310]
}

print(social_data)

{'user_id': [101, 102, 103, 104, 105], 'username': ['luna99', 'max_power', 'sakura_chan', 'data_wolf', 'queenbee'], 'followers': [4520, 1875, 9200, 640, 7310]}


In [31]:
# Convert dictionary to DataFrame
social_df = pd.DataFrame(social_data)
print("Social Media DataFrame:\n")
print(social_df)

# Display DataFrame shape: (rows, columns)
print(f"DataFrame shape: {social_df.shape}")

Social Media DataFrame:

   user_id     username  followers
0      101       luna99       4520
1      102    max_power       1875
2      103  sakura_chan       9200
3      104    data_wolf        640
4      105     queenbee       7310
DataFrame shape: (5, 3)


In [32]:
mixed_data = {
    'user_id': range(1, 6),  # Integers
    'active': [True, False, True, False, True],  # Explicit booleans
    'score': [70, 72, 74, 76, 78]  # Simple sequence of floats
}

mixed_df = pd.DataFrame(mixed_data)
print("\nMixed data types DataFrame:\n")
print(mixed_df)
print(f"\nData types:\n{mixed_df.dtypes}")


Mixed data types DataFrame:

   user_id  active  score
0        1    True     70
1        2   False     72
2        3    True     74
3        4   False     76
4        5    True     78

Data types:
user_id    int64
active      bool
score      int64
dtype: object


Real data generation requires thousands or millions of records. Efficient construction uses NumPy arrays to generate large datasets quickly.

In [33]:
# Generate large dataset efficiently
record_count = 10000

# Direct NumPy array generation
large_data_dict = {
    'record_id': range(1, record_count + 1),
    'category': np.random.choice(['A', 'B', 'C'], record_count),
    'value': np.random.randint(10, 100, record_count),
    'flag': np.random.choice([True, False], record_count)
}

In [34]:
# Convert to DataFrame
large_df = pd.DataFrame(large_data_dict)
print(f"Large DataFrame shape: {large_df.shape}")
print("Sample data:")
# Display the 5 first rows of the DataFrame with head()
print(large_df.head())

Large DataFrame shape: (10000, 4)
Sample data:
   record_id category  value   flag
0          1        A     77   True
1          2        A     85  False
2          3        B     53  False
3          4        B     98   True
4          5        B     89   True


### DateTime generation and manipulation 

Dates and times are among the trickiest data types. Start practicing early so they feel easy later.

Pandas provides dedicated datetime types and tools (e.g., `Timestamp`, `DatetimeIndex`, and `Series` with `datetime64[ns]` dtype) to work with temporal data. With them, you can:

* parse strings into dates,
* extract components (year, month, day, hour),
* perform date arithmetic (shifts, offsets, differences),
* resample and roll up by period,
* handle time zones reliably.

That’s why it’s important to learn how to create and manipulate datetime objects when working with time-based data. This skill is essential for analyzing trends, seasonality, and time-series patterns in your datasets.

#### Date range generation

`pd.date_range()` creates sequences of dates with specified frequency and duration. You control start date, end date, number of periods, and frequency pattern. The frequency parameter accepts various values:

| Frequency Code | Description |
| --- | --- |   
|`'D'` | Daily frequency
|`'W'` | Weekly frequency
|`'M'` | Monthly frequency
|`'h'` | Hourly frequency
|`'T'` | Minutely frequency
|`'S'` | Secondly frequency
|`'L'` | Millisecond frequency
|`'Y'` | Yearly frequency
|`'Q'` | Quarterly frequency

Let's see how to use `pd.date_range()` to generate a sequence of dayly timestamps for a year of social media posts.

In [35]:
# Create a date range for daily timestamps in 2026
daily_dates = pd.date_range(start='2026-01-01', end='2026-12-31', freq='D')

print(f"Daily dates count: {len(daily_dates)}")
print(f"First dates: {daily_dates[:5]}")
print(f"Last dates: {daily_dates[-5:]}")

Daily dates count: 365
First dates: DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05'],
              dtype='datetime64[us]', freq='D')
Last dates: DatetimeIndex(['2026-12-27', '2026-12-28', '2026-12-29', '2026-12-30',
               '2026-12-31'],
              dtype='datetime64[us]', freq='D')


In [36]:
# Date range with specific periods
weekly_dates = pd.date_range(start='2026-01-01', periods=52, freq='W')
print(f"Weekly dates: {len(weekly_dates)} periods")

Weekly dates: 52 periods


In [37]:
# Hourly timestamps
hourly_times = pd.date_range(start='2026-01-01', periods=24, freq='h')
print(f"Hourly timestamps: {hourly_times[:5]}")

Hourly timestamps: DatetimeIndex(['2026-01-01 00:00:00', '2026-01-01 01:00:00',
               '2026-01-01 02:00:00', '2026-01-01 03:00:00',
               '2026-01-01 04:00:00'],
              dtype='datetime64[us]', freq='h')


#### Random timestamp generation

In pandas, you work with time using `pd.Timestamp`. This tool represents one point in time. 

You do not create timestamps one by one. Instead, you usually start with a base or a pattern. Then you apply random changes to simulate natural variation.



In [38]:
# Method 1: Random selection from date range
# Generate 100 random dates in 2023
all_dates = pd.date_range(start='2023-01-01', end='2024-01-01', freq='D')
random_dates = np.random.choice(all_dates, size=100, replace=True)
print(f"Random dates sample: {random_dates[:5]}")

Random dates sample: ['2023-08-01T00:00:00.000000' '2023-11-02T00:00:00.000000'
 '2023-05-14T00:00:00.000000' '2023-08-07T00:00:00.000000'
 '2023-11-15T00:00:00.000000']


In [39]:
# Method 2: Random time deltas
base_date = pd.Timestamp('2023-01-01')
random_days = np.random.randint(0, 365, size=100)

# pd.Timedelta creates time differences to add to base date
random_timestamps = [base_date + pd.Timedelta(days=int(days)) for days in random_days]
print(f"Random timestamps sample: {random_timestamps[:5]}")


Random timestamps sample: [Timestamp('2023-06-04 00:00:00'), Timestamp('2023-08-26 00:00:00'), Timestamp('2023-11-05 00:00:00'), Timestamp('2023-04-10 00:00:00'), Timestamp('2023-09-30 00:00:00')]


## Putting it all together

Let's complete an Instagram-like data generation example. For this example, we will create a synthetic dataset of Instagram posts with the following columns:
* `post_id`: A unique identifier for each post (integer).
* `user_id`: A unique identifier for the user who made the post (integer).
* `account_type`: The type of account (categorical: "personal", "business", "creator").
* `post_date`: The date and time when the post was made (datetime).
* `likes`: The number of likes the post received (integer).
* `comments`: The number of comments the post received (integer).   
* `shares`: The number of times the post was shared (integer).
* `content_type`: The type of content in the post (categorical: "photo", "video", "carousel").

In [40]:
import numpy as np
import pandas as pd

# Set seed for reproducibility
np.random.seed(42)

# Number of records to generate
num_posts = 1000

# Generate post_id and user_id
post_ids = np.arange(1, num_posts + 1)
# 200 unique users
user_ids = np.random.randint(1, 201, size=num_posts)

# Generate account types with specified probabilities
account_types = np.random.choice(['personal', 'business', 'creator'],
                                 size=num_posts, p=[0.7, 0.2, 0.1])

# Generate post dates within the last year
post_dates = pd.to_datetime('2023-01-01') + pd.to_timedelta(
    np.random.randint(0, 365, size=num_posts), unit='D'
)

# Generate likes, comments, and shares using simple random integers
# Business accounts tend to get more likes
likes = np.random.randint(0, 41, size=num_posts) + (account_types == 'business') * 10
# Creator accounts tend to get more comments
comments = np.random.randint(0, 11, size=num_posts) + (account_types == 'creator') * 5
# Personal accounts tend to get slightly more shares
shares = np.random.randint(0, 5, size=num_posts) + (account_types == 'personal') * 1

# Generate content types with specified probabilities
content_types = np.random.choice(['photo', 'video', 'carousel'],
                                 size=num_posts, p=[0.6, 0.3, 0.1])

# Create DataFrame
posts_df = pd.DataFrame({
    'post_id': post_ids,
    'user_id': user_ids,
    'account_type': account_types,
    'post_date': post_dates,
    'likes': likes,
    'comments': comments,
    'shares': shares,
    'content_type': content_types
})

# Display the first few rows of the DataFrame
print(posts_df.head())

   post_id  user_id account_type  post_date  likes  comments  shares  \
0        1      103     personal 2023-12-27     20         1       3   
1        2      180     personal 2023-12-07     17         5       1   
2        3       93     personal 2023-09-15     35        10       4   
3        4       15     personal 2023-09-06     34         9       3   
4        5      107     business 2023-11-27     18         8       4   

  content_type  
0        photo  
1        photo  
2        photo  
3        photo  
4        video  


Let's now export these DataFrames to CSV files for further analysis. To do this, you can use the `to_csv()` method provided by Pandas. This method allows you to save your DataFrame to a CSV file easily.

In [41]:
# Export dataset to CSV files
posts_df.to_csv('simulated_posts.csv', index=False)

<Note type="tip">
`index=False` prevents Pandas from writing row indices to the file, keeping it clean.
</Note> 

## Resources 📚📚

- [NumPy Random Sampling Documentation](https://NumPy.org/doc/stable/reference/random/index.html)
- [Pandas DataFrame Construction Guide](https://pandas.pydata.org/docs/user_guide/dsintro.html#dataframe)
- [Python datetime module](https://docs.python.org/3/library/datetime.html)
- [Pandas Time Series Documentation](https://pandas.pydata.org/docs/user_guide/timeseries.html)
